### ISSUE TITLE
Adobe ColdFusion support

### ISSUE THREAD

**Issue by cfmitrah** [pixl8/sticker#4]
Adobe ColdFusion support

**Comment by DominicWatson** [comment]
Great, thanks for this. Would be good to know what the specific issues are - hopefully nothing fundamental. I could/should also make the test suite for travis run with Adobe CF, I'm just completely out of time right now (and holiday season here in the UK).

**Comment by boughtonp** [comment]
I have a CF11 branch where all except 3 of the tests pass:
  https://github.com/boughtonp/sticker/tree/cf11-compat


For StickerTest renderIncludes, these two work when called directly, but fail when part of the whole suite:

* should prepend JS includes with JS variables include when includeData() has been called
* should render any dependencies that have not been explicity included

I don't see anything that makes a difference between whether they're run direct or with the rest.


For BundleTest +asset('someasset').dependsOn('list','of','assets').dependents('list','of','assets') this one is reversing the order of the array (?!)

* should populate the given asset's before, after, dependsOn and dependents arrays with passed values

I can't figure out what's going on - I don't see anything remotely related to reversing order, the data goes into the array ok, it's just for some reason when it comes out in the dependents function it's coming backwards.

This one doesn't run direct - clicking it returns Skipped: 12 which I guess is a TestBox bug. (Not on latest version, so guess I'll upgrade to check that tomorrow, but the bug itself is going to be because CF11 is crap.)

**Comment by DominicWatson** [comment]
Thanks for the details Peter. Appreciated.

**Comment by KrunchMuffin** [comment]
@boughtonp Have you stopped work on your branch?

**Comment by boughtonp** [comment]
Yeah. For various reasons using Sticker didn't happen, and there's no plans on the horizon to get back to it. If you or anyone wants to pick up where I left it, go ahead.
